@database = inventory
@collection = food
@domain = http://localhost
@port = 3000
###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
  "document": {
    "item": "yogurt",
    "food_group": "dairy",
    "price_in_usd": 0.9,
    "quantity": 80,
    "calories_per_100g": 59,
    "fat_content": "0%"
  }
}

###
@id = 6721a699eb380677ff5c4139
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json
